# Permalinks
permalink:        pretty

# Setup
title:            Ashley Hedberg
tagline:          'Software Engineer'
description:      'Software engineer in Boston, MA.'
url:              http://ahedberg.github.io
baseurl:          /

paginate:         10
paginate_path:    "/blog/page:num/"

author:
  name:           'Ashley Hedberg'
  url:            https://linkedin.com/in/aehedberg

gems:             [jekyll-paginate, jekyll-gist]
